name: Dependabot Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-go@v5
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-docker-compose.yml
      # - run: |
      #     go version
      #     go install github.com/dependabot/cli/cmd/dependabot@latest
      #     dependabot --version
      #     dependabot update github_actions smithjw/tmp-actions
      - run: |
          gh release download \
            --repo "dependabot/cli" \
            --pattern "*linux-amd64.tar.gz" \
            --output "dependabot.tar.gz"
          tar -xzf dependabot.tar.gz
          ./dependabot --version
          ./dependabot update github_actions smithjw/tmp-actions
