name: Dependabot Test

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  issues: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('dependencies.txt') }}
      - run: |
          gh release download \
            --repo "dependabot/cli" \
            --pattern "*linux-amd64.tar.gz" \
            --output "dependabot.tar.gz"
          tar -xzf dependabot.tar.gz
          ./dependabot --version
          ./dependabot update --file job.yml
